site_name: MixFlow
site_description: MixFlow documentation
repo_url: https://github.com/Lotfollahi-lab/mixflow
repo_name: Lotfollahi-lab/mixflow

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.copy

nav:
  - Home: index.md
  - Installation: installation.md
  - Running: running.md
  - Theory & Visualizations: interactive_visualization.md

plugins:
  - search

markdown_extensions:
  - admonition
  - md_in_html
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.superfences
  - attr_list
  - tables
  - toc:
      permalink: true

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
